# Generated by Django 3.2.3 on 2021-06-01 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210531_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='psasword',
            new_name='password',
        ),
    ]
