# Generated by Django 3.2.3 on 2021-06-08 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210601_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='CashInHand',
            field=models.IntegerField(default=50000),
        ),
        migrations.CreateModel(
            name='UserStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StocksOwned', models.CharField(blank=True, max_length=10)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserNetWorth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserNetWorth', models.IntegerField()),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock', models.CharField(max_length=20)),
                ('amountOfStock', models.IntegerField()),
                ('StocksBoughtTime', models.DateTimeField(auto_now_add=True)),
                ('stockBoughtPrice', models.IntegerField()),
                ('StocksSoldTime', models.DateTimeField(blank=True)),
                ('stockSoldtPrice', models.IntegerField(blank=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
