# Generated by Django 3.2.3 on 2021-06-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210608_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhistory',
            old_name='StocksBoughtTime',
            new_name='Time',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='StocksSoldTime',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='stockBoughtPrice',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='stockSoldtPrice',
        ),
        migrations.AddField(
            model_name='userhistory',
            name='isBought',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userstocks',
            name='amountOfStock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='amountOfStock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstocks',
            name='StocksOwned',
            field=models.CharField(max_length=10),
        ),
    ]
