# Generated by Django 3.2.3 on 2021-06-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210609_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='amountOfStock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='isBought',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='userstocks',
            name='amountOfStock',
            field=models.IntegerField(),
        ),
    ]
