# Generated by Django 3.2.3 on 2021-06-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_stocksowned_userstocks_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='CashInHand',
            field=models.IntegerField(blank=True, default=50000),
        ),
    ]
